# Generated by Django 3.2.7 on 2021-09-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
