# Generated by Django 3.2.7 on 2021-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(default='Akash', max_length=30),
        ),
    ]
