# Generated by Django 3.2.7 on 2021-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0012_auto_20211005_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='Last_Updated',
            field=models.DateField(),
        ),
    ]
