# Generated by Django 3.2.7 on 2021-10-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0013_alter_consent_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='Last_Updated',
            field=models.DateTimeField(),
        ),
    ]
