# Generated by Django 3.2.8 on 2021-10-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0014_alter_consent_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='Last_Updated',
        ),
    ]
