# Generated by Django 3.2.8 on 2021-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0015_remove_consent_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='Monthly_Income',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='consent',
            name='funMoneyAllocation',
            field=models.FloatField(default=-1),
        ),
    ]
