# Generated by Django 3.2.8 on 2021-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIU_Main', '0016_auto_20211008_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='Loan',
            field=models.FloatField(default=-1),
        ),
    ]
